### ISSUE TITLE
Plugin and all plugin tools were broken going from 6.1.0 to 6.1.1

### ISSUE THREAD

**Issue by dehoni** [SasView/sasview#3648]
### Initially labelled as Add/Multiply does not work 
in fact, nothing related to plugins seems to work including trying load and use a plugin, add, edit, reparametriaztion etc.

**Describe the bug**
When trying to open Fitting>Add/Multiply Model it produces the error: 
line 1199, in actionAddMult_Models File "sas\qtgui\Utilities\ModelEditors\AddMultEditor\AddMultEditor.py", line 84, in __init__ AttributeError: module 'sas.sascalc.fit.models' has no attribute 'find_plugins_dir'

**To Reproduce**
1. Go to Fitting 
2. Click on Add/Multiply Model

**Expected behavior**
Opening of the Model Creation Window

**Screenshots**

**SasView version (please complete the following information):**
 - Version: 6.1.1

**Operating system (please complete the following information):**
 - OS: Windows 11 and Linux

**Installation method (please complete the following information):**
 - Installed: Windows Installer and ISIS Idaas

**Additional context**
Also when trying to select a Plug-in model in the fitting perspective, it fails with the error:
Traceback (most recent call last): File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 1418, in onSelectModel File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 1589, in respondToModelStructure File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 2364, in SASModelToQModel File "sas\qtgui\Perspectives\Fitting\FittingWidget.py", line 2400, in fromModelToQModel AttributeError: module 'sas.sascalc.fit.models' has no attribute 'find_plugins_dir'

**Comment by smk78** [comment]
Plugins still work in 6.1.0 so this bug was introduced in 6.1.1.

**Comment by butlerpd** [comment]
Ahhh! Thanks Kristian! That indeed sounds like it would be the issue. Though one is led to wonder how such a  change made it into a "bug fix only" release? and if there is anything that can be done to avoid such things in the future?

**Comment by butlerpd** [comment]
Thanks @klytje. I have also started playing with AI tools and recently added github copilot. So far my experience has not been on code exactly but, while the results so far have been mixed for me and show that it is definitely not a panacea (and you cannot use it without seriously engaging your own brain), I've been quite pleasantly surprised at how useful it can be! My hope was that copilot, both the chat and the agentic versions, might be super helpful in the context of SasView? Glad to hear you have been experimenting and found it useful. Would love to talk at contributor camp 

That said, I am still baffled as to why such a move to a whole new module was part of a bug fix? Isn't the motto of a bug fix that "if it ain't broke don't fix it?" And clearly it was not broken since that worked in 6.1.1? Unless it was required to fix some other bug?  In the meantime ... Maybe I'll give a go with copilot to see if it can find all the invocations and update them as an experiment in what it can do?
