### ISSUE TITLE
Deleting an entry under "Theory" in the data explorer results in error

### ISSUE THREAD

**Issue by jack-rooks** [SasView/sasview#2815]
**Describe the bug**
Deleting an entry in the theory tab of the data explorer removes the entry, but results in an error repeated roughly 10 times:

`ERROR: Traceback (most recent call last): File "C:\Users\Jack\GitRepos\sasview\src\sas\qtgui\Perspectives\Corfunc\CorfuncPerspective.py", line 279, in model_changed self.slider.extrapolation_parameters = self.extrapolation_parmameters File "C:\Users\Jack\GitRepos\sasview\src\sas\qtgui\Perspectives\Corfunc\CorfuncSlider.py", line 221, in extrapolation_parameters if self.find_parameter_problems(params) is None: File "C:\Users\Jack\GitRepos\sasview\src\sas\qtgui\Perspectives\Corfunc\CorfuncSlider.py", line 84, in find_parameter_problems if params.data_q_min >= params.point_1: AttributeError: 'NoneType' object has no attribute 'data_q_min'`

This occurs for children of the theory as well (e.g. slicers).

Note that the "Delete" button that is outside of the context menu doesn't work, but also doesn't work in 5.0.5 where the error is not shown.

**To Reproduce**
1. Create a theoretical model (cylinder used, but any works)
2. Right click the entry in the data explorer (if this is the only thing you've done in SasView, it should be "M1 [data]")
3. Select "delete" from the context menu and confirm

**Expected behavior**
Theoretical model should be removed from the list without error. This expected behavior is present in SasView 5.0.5

**SasView version (please complete the following information):**
 - Version: Main branch

**Operating system (please complete the following information):**
 - OS: Windows 10
