### ISSUE TITLE
Unable to save project

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#2888]
**Describe the bug**
While try to save project the following error pops up and project file is not created
06:30:04 - INFO: --- SasView session started, version 6.0.0a1, 2023 ---
06:30:04 - INFO: Python: 3.11.9 (v3.11.9:de54cf5be3, Apr 2 2024, 07:12:50) [Clang 13.0.0 (clang-1300.0.29.30)]
06:30:29 - INFO: 2024-05-26 06:30:29 === Steps: 3 of 200 chisq: 2.01e-06 ETA: 2024-05-26 06:30 (0s from now) M1.radius : 20 |
06:30:50 - ERROR: Traceback (most recent call last): File "sas/qtgui/MainWindow/GuiManager.py", line 833, in actionSave_Project AttributeError: 'NoneType' object has no attribute 'items'

(The same is true with overwriting project files)
**To Reproduce**
1. Load any data file
2. Send it to Fitting 
3. Fit some parameter
4. Try to Save Project from File menu
5. See error

**SasView version (please complete the following information):**
 - Version: 6.0.0a1

**Operating system (please complete the following information):**
 - OS: Mac OSX

**Comment by rozyczko** [comment]
Confirmed not working on Windows as well, with `v6.0.0-beta-1`

**Comment by lucas-wilkins** [comment]
Just tried the alpha on Mac, that seemed ok. I found about 10 other bugs in the process though.

**Comment by wpotrzebowski** [comment]
Indeed, it seems to be fixed now. Closing it.
