### ISSUE TITLE
Missing "alpha_dream" parameter in FittingOptions

### ISSUE THREAD

**Issue by wpotrzebowski** [SasView/sasview#1867]
16:33:32 - ERROR: Traceback (most recent call last):
  File "site-packages/sasview-5.0.4-py3.6.egg/sas/qtgui/Perspectives/Fitting/FittingOptions.py", line 149, in onAlgorithmChange
  File "site-packages/sasview-5.0.4-py3.6.egg/sas/qtgui/Perspectives/Fitting/FittingOptions.py", line 260, in updateWidgetFromBumps
  File "<string>", line 1, in <module>
AttributeError: 'FittingOptions' object has no attribute 'alpha_dream'

It may be related  but "Steps" parameter is missing from the interface (see attached screen shot).  I think it used to set to 0?

![Screenshot 2021-06-03 at 16 33 53](https://user-images.githubusercontent.com/4189922/120663628-7ad14c80-c48a-11eb-8fd4-233ee7676f3f.png)

**Comment by smk78** [comment]
DREAM is working fine in 5.0.4 for me (W10/x64). My Fit Algorithms box looks like this:
![image](https://user-images.githubusercontent.com/10938679/120707475-45d8f000-c4b2-11eb-98fe-3665b3c0c5fd.png)

**Comment by wpotrzebowski** [comment]
Indeed, it is a Mac and I think Linux issue

**Comment by rozyczko** [comment]
Reproduced the issue on Linux.
Windows is OK, as @smk78 noticed.

**Comment by rozyczko** [comment]
Seems ordering of the options mattered but also, we needed a check for new parameters, if they can be displayed in the UI.
`Alpha` wasn't there before so there is no UI element for it.

The ideal situation is to construct the UI dynamically depending on all the exposed parameters, this here is merely a bug fix.
